#!/bin/sh

prefix="/usr"
exec_prefix="${prefix}"
xrdb="xrdb"
xinitdir="/etc/X11/xinit"
xmodmap="xmodmap"
userresources="$XDG_CONFIG_HOME/X11/xresources"
usermodmap="$HOME/.Xmodmap"
sysresources="$xinitdir/Xresources"
sysmodmap="$xinitdir/Xmodmap"

export VAAPI_MPEG4_ENABLED=true
export ADW_DEBUG_COLOR_SCHEME='prefer-dark'
export QT_QPA_PLATFORMTHEME=gtk3
export CM_IGNORE_WINDOW='entryterm'
export NO_AT_BRIDGE=1
export GNOME_ACCESSIBILITY=0
export QT_ACCESSIBILITY=0
export PASSWORD_STORE_CLIP_TIME=40

if [ -f "$sysresources" ]; then
    if [ -x /usr/bin/cpp ] ; then
        "$xrdb" -merge "$sysresources"
    else
        "$xrdb" -nocpp -merge "$sysresources"
    fi
fi
if [ -f "$sysmodmap" ]; then
    "$xmodmap" "$sysmodmap"
fi
if [ -f "$userresources" ]; then
    if [ -x /usr/bin/cpp ] ; then
        "$xrdb" -merge "$userresources"
    else
        "$xrdb" -nocpp -merge "$userresources"
    fi
fi
if [ -f "$usermodmap" ]; then
    "$xmodmap" "$usermodmap"
fi

if [ -d "$xinitdir"/xinitrc.d ] ; then
	for f in "$xinitdir/xinitrc.d"/?* ; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

xset r rate 300 50 &
xset s 3600 3600 &
xsidle.sh ultrabasedlock &
clipmenud &
feh_randomize &
dunst &
(sleep 1s ; dwmblocks) &

exec dwm
