# A TOML linter such as https://taplo.tamasfe.dev/ can use this schema to validate your config.
# If you encounter any issues, please make an issue at https://github.com/yazi-rs/schemas.
"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

[[mgr.prepend_keymap]]
on   = "l"
run  = "plugin smart-enter"
desc = "Enter the child directory, or open the file"

[[mgr.prepend_keymap]]
on   = "i"
run  = "plugin toggle-pane max-preview"
desc = "Maximize or restore preview"

[[mgr.prepend_keymap]]
on   = "B"
run = "shell 'bgs -z $@'"
desc = "Set Background"

[[mgr.prepend_keymap]]
on  = [ "M", "l" ]
run = "plugin mount"

[[mgr.prepend_keymap]]
on  = [ "M", "m" ]
run = "shell 'udevil mount /dev/sda2'"

[[mgr.prepend_keymap]]
on  = [ "M", "b" ]
run = "shell 'udevil mount /dev/sdb1'"

[[mgr.prepend_keymap]]
on  = [ "M", "B" ]
run = "shell 'udevil umount /dev/sdb1'"

[[mgr.prepend_keymap]]
on  = [ "M", "c" ]
run = "shell 'udevil mount /dev/sdc1'"

[[mgr.prepend_keymap]]
on  = [ "M", "C" ]
run = "shell 'udevil umount /dev/sdc1'"

[[mgr.prepend_keymap]]
on  = [ "M", "u" ]
run = "shell 'udevil umount /dev/sda2'"

[[mgr.prepend_keymap]]
on = [ "g", "m" ]
run = "cd /media/"
desc = "Goto mounts" 

[[mgr.prepend_keymap]]
on = [ "g", "C" ]
run = "cd /etc/"
desc = "Goto system configs" 

[[mgr.prepend_keymap]]
on = [ "g", "D" ]
run = "cd ~/Documents"
desc = "Goto Documents" 

[[mgr.prepend_keymap]]
on = [ "g", "v" ]
run = "cd ~/Videos"
desc = "Goto Videos" 

[[mgr.prepend_keymap]]
on = [ "g", "l" ]
run = "cd ~/.local"
desc = "Goto Source Files" 

[[mgr.prepend_keymap]]
on = [ "g", "s" ]
run = "cd ~/.local/src/"
desc = "Goto Source Files" 

