alias sudo='sudo '
alias vim='nvim'
alias svim='sudo nvim'
alias grep='grep --color=auto'
alias ls='ls -F --color=auto --group-directories-first'
alias l='ls -1AF --color=auto --group-directories-first'
alias ll='ls -lahF --color=auto --group-directories-first'
alias fd='fd --hidden --color auto'
alias cp='cp --reflink=auto'
alias pd='pushd'
alias wget='wget --hsts-file=~/.local/state/wget-hsts'
alias info='info --vi-keys'
alias reboot='loginctl reboot'

alias makeconf='sudo nvim /etc/portage/make.conf/02-use.conf'
alias cmakeconf='sudo nvim /etc/portage/make.conf/00-clags.conf'
alias packconf='sudo nvim /etc/portage/package.use'
alias keywconf='sudo nvim /etc/portage/package.accept_keywords'
alias mergefetch='tail -f /var/log/emerge-fetch.log'
alias build-sesh='elogind-inhibit abduco -A portage'
alias attach-sesh='abduco -a portage'

alias bashconf='nvim $HOME/.bashrc'
alias vimconf="nvim ~/.config/nvim/init.lua"
alias recompile='make -j8 clean ; make -j8 ; sudo make -j8 install'
alias cconf='nvim config.h ; make -j8 clean ; make -j8 ; sudo make -j8 install'

alias update-grub='grub-mkconfig -o /boot/grub/grub.cfg'
alias wikigentoo='wikiman -s gentoo'
alias wikiarch='wikiman -s arch'
alias clipclean='cliphist wipe'
alias fontlist='fc-list | cut -f2 -d: | sort -u'
alias scrnsvoff='xset s off -dpms'
alias fzfvim='vim "$(find | fzf --preview "bat {}")"'
alias mp3='cd ~/Music && yt-dlp -x --embed-thumbnail --audio-format mp3'
alias dl-vid='yt-dlp -f "best[ext=mp4]"' 
alias mr='mullvad reconnect'

#alias motherdrive='udevil mount /dev/sda2 && cd ~/.local/media/sda2-ata-Samsung_SSD_870_/'
alias motherdrive='udevil mount /dev/sda2 && cd ~/.local/media/nixos/'
alias umotherdrive='udevil umount /dev/sda2'
alias usbumount='udevil umount'
alias usbmount='udevil mount'
